### ISSUE TITLE
Convert Format: Adobe Illustration (.ai) to SVG

### ISSUE THREAD

**Issue by kausikMR** [Haidar0096/image_magick_q8#4]
Does this package have support to convert a .ai file to .svg or .png.
I need to show a preview for the Adobe Illustrator files in my Flutter desktop app for Windows. Till now I tried to convert the .ai file to .svg, but it does nothing. When I try to convert .svg to .png it works. MagicWand C library supports converting .ai file to any other format.

**Comment by haidarmehsen** [comment]
@kausikMR 
Hello, can you please tell me which function are you using, and are you sure you are using, in this package, the same function that works in your case in the C api?

**Comment by kausikMR** [comment]
Im using like. magicWand.readImageFile('sample.ai');
magicWand.writeImageFile('sample.svg');

when i try to read a .svg image file and then write it as a .png image file, it works fine, but when i try to do the same by reading a .ai file and then write it as .svg, it fails to do the work no exception thrown.

**Comment by haidarmehsen** [comment]
honestly I don't know if IM supports this operation, but I found this comment from one of the maintainers of IM https://github.com/dlemstra/Magick.NET/issues/396#issuecomment-468253248, he says that this operation should not be done by IM, hope it helps.

**Comment by kausikMR** [comment]
I know its not the proper way and Also heard that ImageMagick doesnt suit for the job, but I knew a library **QuickLook** [https://github.com/QL-Win/QuickLook](https://github.com/QL-Win/QuickLook) which uses the ImageMagick to show preview for the .ai files. It works fine and shows the preview, I need to achieve that using your package.

**Comment by haidarmehsen** [comment]
My package is just a delegate to the C api, so the real work is being done by the C api.

Basically anything available in the C api can be done with this package bcz as I said above, I am just delegating the work to the C api. However, there are very rare cases where the C api methods cannot be used from this package, in this case I didn't include the bindings to these methods.

As for the existing methods, if you are running a command on an image and seeing no effect, try using `magickGetException` to see if the underlying C api is throwing any exceptions

**Comment by kausikMR** [comment]
**Logs**:
flutter: input: C:\Users\kausikMR\Desktop\example.ai
flutter: Error: MagickException{severity: ExceptionType.DelegateError, description: FailedToExecuteCommand `"gs" -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -dPrinted=false  "-sOutputFile=C:/Users/kausikMR/AppData/Local/Temp/magick-W6FNV8zBxaXABMkW1OtXTGsYwJ2AxOeF%d" "-fC:/Users/kausikMR/AppData/Local/Temp/magick-icnw5q0ZjmKqJ8Q0bjDP8_ScMPVWsyrD" "-fC:/Users/kausikMR/AppData/Local/Temp/magick-xRCUJlUHZS0joJuoweq5o1aAZrzEmjvY"' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/516}
flutter: outpath C:\Users\kausikMR\Desktop\example.svg
flutter: Error: MagickException{severity: ExceptionType.WandError, description: ContainsNoImages `MagickWand-1' @ error/magick-image.c/MagickWriteImage/13278}
flutter: Completed! outpath C:\Users\kausikMR\Desktop\example.svg

Above you can see when I give example.ai and then write it as example.svg.

**Comment by haidarmehsen** [comment]
@kausikMR are you sure the file exists and you have the permissions?

my suggestion to debug correctly:
1- run the same command in plain C imagemagick's code and see if it works
2- if "1" worked, then make sure you have the necessary permissions in flutter, maybe using `permission_handler: ^10.2.0`
 
And tell me the results and the logs please

**Comment by kausikMR** [comment]
@haidarmehsen Permissions won't be a problem I guess because I tried converting a SVG file from the same path and it works fine.

**Comment by kausikMR** [comment]
I tried using ImageMagick desktop app and it seems Ai files doesn't work. so I'm closing this issue thank you for your support @haidarmehsen.
